aws_region          = "us-west-2"
project_name        = "mediaflow"
environment         = "dr"
account_id          = "969430605054"
domain_name         = ""
acm_certificate_arn = ""
ses_email           = "senanetworker@gmail.com"
